/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 04 14:33:46 GMT 2019
 */

package club.chenlinghong.demo.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import club.chenlinghong.demo.evosuite.EvosuiteDemo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EvosuiteDemo_ESTest extends club.chenlinghong.demo.evosuite.EvosuiteDemo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvosuiteDemo evosuiteDemo0 = new EvosuiteDemo();
      String string0 = evosuiteDemo0.evosuite((-803), "");
      assertEquals("0#name -1", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvosuiteDemo evosuiteDemo0 = new EvosuiteDemo();
      String string0 = evosuiteDemo0.evosuite(0, "oame");
      assertEquals("0#name -1", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EvosuiteDemo evosuiteDemo0 = new EvosuiteDemo();
      String string0 = evosuiteDemo0.evosuite(0, "name");
      assertEquals("0#name", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvosuiteDemo evosuiteDemo0 = new EvosuiteDemo();
      String string0 = evosuiteDemo0.evosuite(343, "0#name");
      assertEquals("0#name 1", string0);
  }
}
